src/components/Hero/_hero.scss
src/views/LandingPage/_landingpage.scss
src/views/WhyVotePage/WhyVotePage.vue

This PR addresses some small issues with mobile friendly and responsiveness.
##Fixes Multiple UI issues expressed from designer.
Tested locally in dev environment

Fit and finish

---

src/components/Hero/_hero.scss

Signed-off-by: syd bailey <syd@syds-MacBook-Pro.local>

changed button height on hero

---

package.json
src/main.js
yarn.lock

fix(dependecies): remove iframe-resize #118
Signed-off-by: David Nixon <david_nixon@us.ibm.com>

fix(dependencies): remove iframe-resizer

---

README.md

This addresses the Read Me page with to update the verbiage with new text provided by @yrabun and approved by @drealuc 
You can see [the document here](https://ibm.ent.box.com/file/733400051445?s=c9f9x3oout8tz6t8l8n052qyhn73y1i3&utm_campaign=collab%20auto%20accept%20user&utm_medium=email&utm_source=trans).
Please reach out to @yrabun or @drealuc if you need access to this file. 
Please delete options that are not relevant.
Locally in dev env
Signed-off-by: Syd <sydabailey@gmail.com>

feat(readMe): updated with new verbiage provided by Yolanda

---

services/twitter/Chatter.py
src/components/Countdown/Countdown.vue

Mitigate the twitter error #142
Set count down clock to January 5, 2021 for the Ga senate runoff

Twitter fix + countdown clock

---

src/components/Maps/GoogleMapMarker.vue

Signed-off-by: David Nixon <david_nixon@us.ibm.com>

fix: build break

---

tests/selenium/README.md
tests/selenium/build/README.md
tests/selenium/issues/README.md
tests/selenium/livesite/README.md
tests/selenium/manual/FiveFifthsVoter.side
tests/selenium/manual/README.md

Addressing #136 by putting basic structure and a sample in place to test roundtrip with non-developer tester on live site manually activated, automated test with Selenium.

Selenium Manual UI Testing Framework

---

ui/src/components/TwitterChatter/_twitterchatter.scss

**Updated Page:** 
https://www.fivefifthsvoter.com/#/connect
localhost:3000/connect
- Added color legend for sentiments
- Added sentiment color border for tweets
**Before:** 
**After:**

Update get connected tweet list

---

.github/workflows/stale.yml

adding stale bot to the repository

---

.github/workflows/stale.yml

@GeraldMit, I increased the days before the issue is closed to 30 as discussed in the call. Please review and merge. Thank you!
@aleggett23 @cstefano1 @Sabine-Justilien @demilolu

increasing stale bot days-before-close

---

ui/package.json
ui/src/components/MarkDown/MarkDown.vue
ui/src/components/MarkDown/index.js
ui/src/plugins/en.json
ui/src/views/WhyVotePage/WhyVotePage.vue
ui/vue.config.js
ui/yarn.lock

add markdown component for translated strings

---

tests/selenium/manual/FiveFifthsVoter.side
ui/src/views/SupportPage/SupportPage.vue

Replaced the child care URL. 
@davidnixon I also replaced in the selenium test. Not sure if that was required. Please review and merge.
Fixes #203 
FYI @Sabine-Justilien @demilolu @cstefano1

fixing issue 201 - update child care resources

---

ui/src/views/LandingPage/LandingPage.vue

Fixes issue #220 
@davidnixon @GeraldMit pls review and merge
FYI @demilolu @Sabine-Justilien @cstefano1

fixing issue 220 - quote does not show up

---

doc/USERGUIDE.md
tests/selenium/manual/FiveFifthsVoter.side
ui/src/components/AppHeader/AppHeader.vue
ui/src/router.js

as discussed in #217 
@davidnixon @GeraldMit pls review and merge.
@demilolu @Sabine-Justilien

Removing get connected page from the code

---

.gitignore

ignore yarn 2+ files for now

---

.github/workflows/build-ui.yml

Adding GitHub action to install, build and test the UI component on every
- commit to any branch
- PR to the main branch
The action does the following
- for all configurations in the matrix (currently just Node.js 14)
- install dependencies - making sure package.json file is valid and there are no major security issues from npm
- cache dependencies for next run
- build the production site
- run unit tests
- run yarn lint
If all of the above passes, new code can be merged in.
Sample run - https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/runs/3682040517?check_suite_focus=true
Related to #232 
@davidnixon @GeraldMit: pls review and merge. I also had to comment out the default test that comes with vue.js. It fails as we don't have the `helloworld` component in this …

GitHub action to test UI before merging code

---

ui/tests/unit/example.spec.js

@GeraldMit as per [conversation](https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/pull/233/files/dd6ef0268abf836cd4c99a07ff6927d35af2c830#r716220440).
If I comment out the whole file, I get an error saying `Test suite failed to run. Your test suite must contain at least one test.`. 
Instead, I will change describe as follows, so it's clear that this is just an example.
```
describe('TestSample.vue', () => {
it('sample test', () => {
expect(true);
});
});
```
We need a general unit testing issue. #136 seems only for Selenium.

cleaning up the sample test

---

ui/src/plugins/en.json
ui/src/views/SupportPage/SupportPage.vue

Contributes to #236 
- changed languge
- changed location of text
See issue
Yes, tested locally. 
@Sabine-Justilien, pls confirm the result.

fixing issue 236. Language and position change

---

ui/src/components/EarlyVoting/EarlyVoting.vue
ui/src/plugins/en.json

- updated as per @Sabine-Justilien suggestion
- extracted string for translation

fixing 228, updating message for no results from civic api

---

ui/src/plugins/en.json
ui/src/views/SupportPage/SupportPage.vue

Contributes to #211 
- added LA specific link as described in #211
- the commit says fixing 236. That message is incorrect. This commit fixes 211.
- Asked by @Sabine-Justilien 
- Yes, tested locally.
- @Sabine-Justilien pls confirm the screenshot

fixing issue 211. Adding LA specific links

---

ui/src/components/EarlyVoting/EarlyVoting.vue
ui/src/plugins/en.json

Contributes to #229
- see details in issue
- as directed by @Sabine-Justilien 
- tested locally
- @Sabine-Justilien, pls confirm image here

fixing issue 229. Adding new para to voting journey

---

ui/src/components/Register/Register.vue
ui/src/plugins/en.json

Fixes #210 
@Sabine-Justilien @demilolu

Ul youth 210

---

ui/src/components/Absentee/Absentee.vue
ui/src/components/AppHeader/AppHeader.vue
ui/src/components/BallotReturn/BallotReturn.vue
ui/src/components/EarlyVoting/EarlyVoting.vue
ui/src/components/Hero/Hero.vue
ui/src/components/PageLayout/PageLayout.vue
ui/src/components/Register/Register.vue
ui/src/components/VoteNow/VoteNow.vue
ui/src/plugins/en.json
ui/src/views/JourneyPage/JourneyPage.vue
ui/src/views/SupportPage/SupportPage.vue
ui/src/views/WhyVotePage/WhyVotePage.vue

Contributes to #246
Worked on punch list from slack.
Tested locally

Fix punch list sep28

---

ui/src/components/AppHeader/AppHeader.vue

Contributes to #250 
Fix mobile nav
Locally with browser tools

fix mobile menu that I broke :-( fixes #250

---

ui/src/App.vue
ui/src/components/AppHeader/AppHeader.vue
ui/src/components/Countdown/_countdown.scss
ui/src/plugins/en.json
ui/src/plugins/i18n.js

Contributes to # (add issue number here. i.e. `#302`)
#222
#213
1) change size of count down timer
2) add a dropdown for languages
3) change language selection to native language name for the language
for issues as given
local build
- [x ] Fixes entire issue

countdownAndlanguagedropdown

---

ui/public/.well-known/assetlinks.json

Contributes to # (add issue number here. i.e. `#302`)
Added TWA json file
Google TWA needs this file for trusting web activity
Yes, tested locally with `yarn build`

adding asset link file for production application

---

doc/GETSTARTED.md

Tweak the getting started doc to work with my new Fedora install

tweak getting started doc for Fedora

---

.github/workflows/deployment.yml
.gitignore
services/blue.yml
services/manifest-blue.yml
ui/blue.yml
ui/manifest-blue.yml

Contributes to #272 
Added ci/cd action for ui and services
Automate ci/cd
Yes, tested locally with act

Adding ci/cd for ui and services blue version

---

services/package.json
ui/src/views/JourneyPage/JourneyPage.vue
ui/src/views/JourneyPage/_journeypage.scss

- Changes text & hover background color on Journey tabs. 
- Also removed the header shrinking on this journey page as it was not cooperating with other changes
- Added fix for services deploy error
The text was dark gray on black and so was unreadable.
Locally

Fix journey tabs

---

.github/workflows/deployment.yml
services/.cfignore
services/package.json

Contributes to #306 - partial fix - fixed services deployment for CF

fix deployment to blue service & skip postinstall for deployment

---

.github/workflows/deployment-vNext.yml

Fix: deployment action

---

ui/src/api/access-api.js
ui/src/api/elections-api.js
ui/src/store/modules/store-teams.js
ui/src/views/TeamPage/ContestView.vue
ui/src/views/TeamPage/RemoveCandidate.vue
ui/src/views/TeamPage/TeamPage.vue

- Twitter URLs were not displaying
- Browser was caching contest docs too long
- Suppress tab error when leaving team page
- Allow candidate to be deleted

Fix: "my list" issues

---

services/api/controllers/controller-shared.js
services/api/models/model-badge.js
services/api/models/model-share.js
services/api/routes/route-shared.js
services/app.js
ui/src/api/share-api.js
ui/src/store/index.js
ui/src/store/modules/store-shared.js
ui/src/views/TeamPage/AddCandidate.vue
ui/src/views/TeamPage/AddContest.vue
ui/src/views/TeamPage/AddElection.vue
ui/src/views/TeamPage/MyList.vue
ui/src/views/TeamPage/ShareList.vue
ui/src/views/TeamPage/TagCandidate.vue

Add a way to anonymously share a list & tags.
Help collaborate

Chore: my list sharing

---

.github/workflows/deployment.yml
ui/src/api/base58id.js
ui/src/api/dateFormatter.js
ui/src/components/EarlyVoting/index.js
ui/src/components/Maps/GoogleMap.vue
ui/src/components/Maps/GoogleMapLoader.vue
ui/src/components/Maps/GoogleMapMarker.vue
ui/src/components/Register/_register.scss
ui/src/data/usa-2022-midterms-info.json
ui/src/plugins/en.json
ui/src/store/modules/user.js
ui/src/views/JourneyPage/CivicData.vue
ui/src/views/JourneyPage/EarlyVoting.vue
ui/src/views/JourneyPage/JourneyPage.vue
ui/src/views/JourneyPage/LocationList.vue
ui/src/views/JourneyPage/_earlyvoting.scss
ui/src/views/JourneyPage/_journeypage.scss

Contributes to #336 
Add code to implement design for midterm 2022 voting page.
- Update Journey in-page nav based on discussion on Wed status call. Using Carbon progress bar for nav
- Removed geocoding of voters address due to uncertain $$ costs
- Early vs day of voting location displayed based on date rather than having 2 buttons.

Feat midterm2022 vote

---

ui/src/components/AppHeader/AppHeader.vue

Signed-off-by: Vinay Kushwaha <iamvinayvk@gmail.com>
Contributes to #365 
- Added the Instragam icon on the header
- Linked the Icon to the 5/5 Instagram page feed
for fixing the issue as given
- local build
- checked on different screen sizes

added instagram button on header

---

doc/GETSTARTED.md

Signed-off-by: Sneha Varghese snehaoffice024@gmail.com
See details at https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/issues/367
Contributes to # (add issue number here. i.e. `#302`) - #367 
Updated Get Started guide
Get Started guide was missing a few steps. So updated to make the local setup experience better
Followed the instructions to setup on my local machine

Updates to GetSTARTED guide, issue #367

---

.github/workflows/certbot-schedule.yml

fix: certbot action

---

.github/workflows/cypress-e2e.yml
.github/workflows/lint.yml
app/components/Home/Header.vue
app/components/Home/Values/Card.vue
app/components/Home/Values/Section.vue
app/components/Journey/LocationList.vue
app/components/LanguagePanel.vue
app/components/TheHeader.vue
app/cypress.config.js
app/cypress/e2e/smoke.cy.js
app/cypress/fixtures/example.json
app/cypress/support/commands.js
app/cypress/support/e2e.js
app/nuxt.config.ts
app/package-lock.json
app/package.json
app/pages/index.vue
app/server/api/auth/[...].js

Contributes to # (add issue number here. i.e. `#302`)
add e2e tests with Cypress

test: add e2e and lint PR tests

---

app/components/Journey/BallotReturn.vue
app/components/Journey/Candidates/ByState.vue
app/components/Journey/FAQ.vue
app/components/Journey/GetInformed.vue
app/components/Journey/RegisterToVote.vue
app/components/Journey/VoteInPerson.vue
app/components/Page/Title.vue
app/components/VoterSupport/Link.vue

An upgrade to lint added some rules for tailwind which left a few files with lint errors.
Cleaned those up.

build: fix lint issues

---

app/package-lock.json

chore: npm audit fix

---

app/components/Journey/SubNav.vue

fix: sub nav current bg should match main header

---

app/content/elections/wi/2026-spring.yml
app/content/procedures/Wisconsin.yml
package-lock.json

Generated Wisconsin files using these prompts.
Can you use the date in usa-2024 and the procedure schema to create a Wisconsin.yml file. Use the Georgia.yml as an example only. The data for Wisconsin should be come from usa-2024
Let me search for Wisconsin's data in the usa-2024.json file and create a Wisconsin.yml file following the structure shown in Georgia.yml and conforming to the procedure schema.I'll continue looking through the data differently to find Wisconsin's information.Based on the schema and the data from usa-2024.json, I'll create a Wisconsin.yml file following the same structure as Georgia.yml but with Wisconsin-specific data. Here's the Wisconsin.yml content:
```yaml
region_code: wi
region: Wisconsin
early_voting:
available: true
id_needed: true
more_link: …
```

feat: add content for Wisconsin
